[theme]
primaryColor = "#00d4ff"
backgroundColor = "#0a0e27"
secondaryBackgroundColor = "#1a1a2e"
textColor = "#e0e0e0"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = true
maxUploadSize = 200

[browser]
gatherUsageStats = false
